# Generated by Django 5.2.4 on 2025-07-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0002_chat_conversation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='conversation',
        ),
        migrations.AddField(
            model_name='chat',
            name='messages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
